---
:data: &default
  :name: Tim Wade
  :address: 2525 NE 50th Ave, Portland, OR
  :telephone: (706) 248-7589
  :email: hello@timjwade.com
  :profile: []
  :work_history:
    - :title: Software Engineer
      :dates: 2015 - Present
      :employer: Red Hat
      :city: Portland
      :state: OR
      :achievements:
        - >
          Built new endpoints for the existing JSON API while tackling
          technical debt, promoting RESTful principles, and did
          foundational work on a new version of the API implemented to
          the GraphQL specification.

        - >
          Designed and implemented the service order API, allowing
          users to compose new services from items in a catalog, one
          of the key features of the Self Service UI.

        - >
          Implemented a SQL-based session store that could be
          configured to allow customers to scale their appliance
          horizontally to fit their needs.

        - >
          Identified and addressed critical security issues promptly
          and professionally.

        - >
          Initiated the Last Week in ManageIQ blog series and continue
          to contribute to it regularly.

    - :title: Ruby Engineer
      :dates: 2014 - 2015
      :employer: The Mobile Majority
      :city: Santa Monica
      :state: California
      :achievements:
        - >
          Developed bid pacer service for large MongoDB-backed ad
          management tool, allowing compaigns to spread their budget
          evenly over the course of the campaign.

        - >
          Extended Rails' own configuration to allow DevOps engineers
          to configure and spin up arbitrary environments.

        - >
          Built out much of the RESTful API in Rails, providing a
          gateway for all backend microservices.

    - :title: Lead Developer
      :dates: 2012 - 2014
      :employer: Peachtree Medical Billing
      :city: Athens
      :state: GA
      :achievements:
        - >
          Built an application that parses EDI documents and posts
          payments to Peachtree's internal software, performing hours
          of work in a matter of seconds.  Contributor to the
          Stupidedi gem.

        - >
          Spearheaded future development of internal software by
          breaking up a monolithic large code base into
          smaller. pluggable packages and applications and guiding
          development out of Ruby 1.8.7 and into 2.1

        - >
          Led end—to—end development and training in a team of up to
          3 other developers. Introduced them to TDD and BDD. pair
          programming, wrote much of the test suite, and initiated a
          series of tech talks to promote best practices and new
          technologies.

        - Administered Linux, Gitolite, Gitlab and MySQL servers.

    - :title: Pianist and Music Teacher
      :dates: 2009-2012
      :employer: self
      :city: London

    - :title: Bookseller
      :dates: 2002-2009
      :employer: "Harrods Children's Books/Waterstone's"
      :city: London

  :community:
    :other:
      - Wrote and talked about TDD and other aspects of testing
      - Regular contributor to This Week in Rails newsletter and blog series
      - Contributed to RSpec, Rails, Brakeman, Rubocop, among other projects.
      - Hosts Ruby Coworking for pdx.rb and films their monthly meetups for their YouTube channel

  :education:
    - :institution: Goldsmiths, University of London
      :years: 2005-8
      :city: London
      :qualification: BMus Classical Music (1st class honours)

:profiles:
  :main:
    <<: *default
    :profile:
      - >
        Software Engineer for a leading Open Source company with a
        passion for Ruby, Open Source, TDD and clean code. Experience
        in engineering software solutions for cloud computing, medical
        billing and mobile advertising. Expertise in Object Oriented
        Design, RESTful APIs and working with legacy code.
