---
:data: &default
  :name: Tim Wade
  :address: 2525 NE 50th Ave, Portland, OR
  :telephone: (706) 248-7589
  :email: hello@timjwade.com
  :profile: []
  :work_history:
    - :title: Software Engineer
      :dates: 2015 - Present
      :employer: Red Hat
      :city: Portland
      :state: OR
      :achievements:
        - >
          Refactored a monolithic, legacy Rails application into more
          object-oriented code with smaller objects and more isolated
          unit testing following best practices and "The Rails
          Way". Deleted dead code and replaced home-grown solutions
          by with popular and battle-tested open source alternatives.

        - >
          Added many new features and endpoints to the existing JSON
          API, trying to follow RESTful principles where possible in
          an existing API that is a mixture of REST and RPC.

        - >
          Identified and addressed several critical security issues
          promptly and professionally.

        - >
          Initiated the Last Week in ManageIQ blog series and continue
          to contribute to it regularly.

    - :title: Ruby Engineer
      :dates: 2014 - 2015
      :employer: The Mobile Majority
      :city: Santa Monica
      :state: California
      :achievements:
        - >
          Built out much of the RESTful API in Rails, conforming to
          JSON API standards using ActiveModel::Serializers
        - Added much of the test suite used for internal tools
        - >
          Developed bid pacer for large MongoDB-backed ad management
          tool, allowing compaigns to spread their budget evenly over
          the course of the compaign.

    - :title: Lead Developer
      :dates: 2012 - 2014
      :employer: Peachtree Medical Billing
      :city: Athens
      :state: GA
      :achievements:
        - >
          Principle developer on an application that parses EDI
          documents and posts payments to Peachtree's internal
          software, performing several hours of work in a matter of
          seconds.  Contributor to the Stupidedi gem.

        - >
          Spearheaded future development of internal software by
          breaking up a monolithic large code base into
          smaller. pluggable packages and applications and guiding
          development out of Ruby 1.8.7 and into 2.1

        - >
          Led end—to—end development and training in a team of up to
          3 other developers. Introduced them to TDD and BDD. pair
          programming, wrote much of the test suite, and initiated a
          series of tech talks to promote best practices and new
          technologies.

        - Administered Linux, Gitolite, Gitlab and MySQL servers.

    - :title: Self-employed
      :dates: 2009-2012
      :employer: self
      :city: London

    - :title: Bookseller
      :dates: 2002-2009
      :employer: "Harrods Children's Books/Waterstone's"
      :city: London

  :internships:
    - :title: Satchidananda Ashram Kitchen Internship
      :year: 2012
      :city: Yogaville
      :state: VA

  :certificates:
    - CELTA, Cambridge English Language Assessment

  :community:
    :blogposts:
      - :title: Testing JSON APIs with RSpec Composable Matchers
        :link: http://timjwade.com/2016/08/01/testing-json-apis-with-rspec-composable-matchers.html
      - :title: "Factories Aren't Fixtures"
        :link: http://timjwade.com/2017/02/20/factories-arent-fixtures.html
    :talks:
      - :title: What We Talk About When We Talk About Unit Testing
        :link: https://www.youtube.com/watch?v=Pb8THg0-lo8
    :other:
      - Regular contributor to This Week in Rails newsletter and blog series
      - Contributed to RSpec, Rails, Brakeman, Rubocop, among other projects.

  :skills:
    - Ruby
    - Ruby on Rails
    - Git
    - TDD
    - Linux
    - Lisp
    - Bash
    - Emacs
    - RESTful APIs
    - Object Oriented Design

  :education:
    - :institution: Goldsmiths, University of London
      :years: 2005-8
      :city: London
      :qualification: BMus Classical Music (1st class honours)

:profiles:
  :main:
    <<: *default
    :profile:
      - >
        Software Engineeer for a leading Open Source company with a
        passion for Ruby, Open Source, TDD and clean code. Experience
        in engineering software solutions for cloud computing, medical
        billing and mobile advertising, and working with legacy code.
