---
:data: &default
  :name: Amanda Irwin
  :address: 2525 NE 50th Ave, Portland, OR
  :telephone: (404) 718-9925
  :email: a00irwin@gmail.com
  :profile: []
  :work_history:
    - :title: Barista
      :dates: February - December 2015
      :employer: Cafe Demitasse
      :city: Santa Monica
      :state: CA
      :achievements:
        - >
          Made latte art and concocted original drink recipes in a
          thriving and bustling downtown Santa Monica promenade
          location. Trained new hires in all aspects of pulling the
          perfect shot and running a clean and tight
          kitchen. Keyholder.

        - >
          Solely responsible for developing and delivering unique
          seasonal products in all 3 stores across Los Angeles. Planned
          and executed on logistics for running a stall at outdoor
          events around Los Angeles.
        - >
          Managed product line and inventory for online store. Managed
          the website using Spark Pay. Created content for the website,
          including copy and photography.

    - :title: "Owner's Assistant"
      :dates: 2006, 2007, 2009, 2013, 2015 (seasonal)
      :employer: Yoga Oasis
      :city: Pahoa
      :state: HI
      :achievements:
        - Managed calendar, e-mails, website, reception
        - Did bookings and finance
        - Worked full time in guest services and in the kitchen

    - :title: Deli Team Member
      :dates: July 2014 - January 2015
      :employer: Daily Groceries
      :city: Athens
      :state: GA
      :achievements:
        - Managed inventory, budgets and cost sheets for new products in the deli.
        - Designed and created labels for new products using Adobe InDesign.
        - Trained in all aspects of food preparation and kitchen management.

    - :title: Server
      :dates: June 2012-July 2015
      :employer: Trappeze Pub
      :city: Athens
      :state: GA
      :achievements:
        - Server, hostess, and expo for a renowned craft beer pub.
        - >
          Researched brew methods, styles and kept current with
          innovations and new beers that were constantly coming out.
        - >
          Delivered consistently excellent service in an extremely high
          volume and fast paced environment.

    - :title: Race coordinator
      :dates: August 2010 - June 2011
      :employer: Classic Race Services
      :city: Athens
      :state: GA
      :achievements:
        - Coordinated 5k races for up to 300 participants and keeping score.
        - MC for Awards.

    - :title: Line Manager
      :dates: August 2007-August 2008
      :employer: Einstein Bagel
      :city: Lawrenceville
      :state: GA
      :achievements:
        - Managed and trained a team of 4-5 people.
        - Barista, Cashier, Food preparation

    - :title: Assistant Manager
      :dates: January 2005-2010 (seasonal)
      :employer: Shields Market
      :city: Atlanta
      :state: GA
      :achievements:
        - >
          Responsible for money, inventory, merchandising, food
          prepartion, customer service, cashier.
        - Innovated product line and contributed recipes for deli

  :internships:
    - :title: UGA UGarden Organic Farming Internship
      :year: 2014
      :city: Athens
      :state: GA
      :achievements:
        - Organized volunteer program.
        - >
          Taught organic and local food concepts and farming
          techniques to students.
        - Drove a tractor.
    - :title: Satchidananda Ashram Kitchen Internship
      :year: 2012
      :city: Yogaville
      :state: VA
      :achievements:
        - Preparing vegetarian and ayurvedic meals for 100+ guests and employees.
        - Participated in a special event to cater for over 500 people.
        - Trained kitchen staff in food preparation.

  :certificates:
    - >
      Received 200 hour RYT certification for Yoga instruction at Vastu
      School of Yoga and led my own yoga classes
    - UGA Local Food Certificate

  :skills:
    - InDesign
    - Photoshop
    - Word
    - Excel
    - Powerpoint
    - Outlook
    - Pages
    - Numbers
    - Keynote
    - HTML
    - CSS
    - Latte Art

  :other:
    - >
      Farmed in France for three months through WWOOFing to learn French
      language, culture and organic farming practice.
    - >
      Volunteer yoga teacher in nursing homes and donation-based yoga at
      Rubber Soul in Athens, GA.
    - Volunteered hospice care in Pahoa, HI.

  :education:
    - :institution: University of GA
      :years: 2008-14
      :city: Athens
      :state: GA
      :qualification: BA English Literature and Film

    - :institution: Collins Hill High School
      :years: 2008
      :city: Lawrenceville
      :state: GA
      :qualification: HS Diploma, Graduated with Honors

:profiles:
  :food:
    <<: *default
    :profile:
      - >
        Amanda is a multitalented Barista, Server and Cook with a
        passion for quality, locality, the seasonal and unexpected
        pairings.

      - >
        She adores cinema, books and ideas which led her to pursue a
        BA in English and Film at UGA which she completed in
        2014. Around that time she enjoyed a multitude of
        extracurricular activities, among them: rowing for the UGA
        team, organic farming, pottery, painting, cooking, yoga,
        music, and many other crafts.

      - >
        She is especially passionate about food and farming and their
        relationship to the community and the environment. It is her
        dream to one day own a cafe or food cart that embodies all of
        her loves.
