---
:data: &default
  :name: Tim Wade
  :address: 2603 SE 51st Ave, Portland, OR
  :telephone: (706) 248-7589
  :email: hello@timjwade.com
  :profile: []
  :work_history:
    - :title: Lead Software Engineer
      :dates: 2020 - Present
      :employer: Heroku (Salesforce)
      :city: Portland
      :state: OR
    - :title: Senior Software Engineer
      :dates: 2018 - 2020
      :employer: Heroku (Salesforce)
      :city: Portland
      :state: OR
      :achievements:
        - >
          Led and mentored a team in PostgreSQL query optimization for
          Heroku's core database in 2019, and continues to lead
          efforts to maintain and improve good query performance to
          provide the best possible experience for users of the Heroku
          API.

        - >
          Added MFA, device activation and account recovery to Heroku
          authentication, giving users more flexibility in securing
          their data, while reducing the internal cost of abuse to the
          platform.

        - >
          Led efforts to adapt parts of our Identity application for
          general use and extract them into a privately maintained
          gem, allowing other components in our platform to integrate
          with other services within Salesforce effortlessly.

    - :title: Software Engineer
      :dates: 2015 - 2018
      :employer: Red Hat
      :city: Portland
      :state: OR
      :achievements:
        - >
          Designed and implemented the service order API, allowing
          users to compose new services easefully from items in a
          catalog.

        - >
          Implemented a SQL-based session store that could be
          configured to allow customers to scale their appliance
          horizontally to fit their needs.

        - >
          Initiated the Last Week in ManageIQ blog series to both
          promote the latest developments to our platform and better
          engage with the Open Source community

    - :title: Ruby Engineer
      :dates: 2014 - 2015
      :employer: The Mobile Majority
      :city: Santa Monica
      :state: California
      :achievements:
        - >
          Developed bid pacer service for large MongoDB-backed ad
          management tool, allowing compaigns to spread their budget
          evenly over the course of the campaign.

    - :title: Software Developer
      :dates: 2012 - 2014
      :employer: Peachtree Medical Billing
      :city: Athens
      :state: GA
      :achievements:
        - >
          Built an application that parses EDI documents and posts
          payments to Peachtree's internal software, performing hours
          of work in a matter of seconds.  Contributor to the
          Stupidedi gem.

        - >
          Led end—to—end development and training in a team of up to
          3 other developers. Introduced them to TDD and BDD. pair
          programming, wrote much of the test suite, and initiated a
          series of tech talks to promote best practices and new
          technologies.

    - :title: Pianist and Music Teacher
      :dates: 2009-2012
      :employer: self
      :city: London

    - :title: Bookseller
      :dates: 2002-2009
      :employer: "Harrods Children's Books/Waterstone's"
      :city: London

  :community:
    :other:
      - Regular contributor to This Week in Rails newsletter and blog series.
      - Contributed to RSpec, Rails, Brakeman, Rubocop, among other projects.
      - Currently working on expanding APIs for configuring Content Security Policy in Rails
      - Hosted Ruby Coworking for pdx.rb (on hiatus owing to Covid).

  :education:
    - :institution: Goldsmiths, University of London
      :years: 2005-8
      :city: London
      :qualification: BMus Classical Music (1st class honours)

:profiles:
  :main:
    <<: *default
    :profile:
      - >
        Software Engineer with a passion for Ruby, PostgreSQL and
        TDD. Experience in engineering software solutions for cloud
        computing, medical billing and mobile advertising. Expertise
        in Object Oriented Design, RESTful APIs, PostgreSQL and
        working with legacy code.
